# This workflow will build and push a web application to an Azure Static Web App when you change your code.
#
# This workflow assumes you have already created the target Azure Static Web App.
# For instructions see https://docs.microsoft.com/azure/static-web-apps/get-started-portal?tabs=vanilla-javascript
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZ_SUBSCRIPTION with the value of your Static Web Apps deployment token.
#    For instructions on obtaining the deployment token see: https://docs.microsoft.com/azure/static-web-apps/deployment-token-management
#
# 2. Change the values for the AZ_SUBSCRIPTION, AZ_STORAGE_ACCT_NAME environment variables (below).
#    For instructions on setting up the appropriate configuration values go to https://docs.microsoft.com/azure/static-web-apps/front-end-frameworks
name: Deploy foodforestfolks.com

on:
  workflow_dispatch:

# Environment variables available to all jobs and steps in this workflow
env:
  SRC_DIR: .
  AZ_SUBSCRIPTION: ${{ secrets.AZ_SUBSCRIPTION }}
  AZ_STORAGE_ACCT_NAME: ${{ secrets.AZ_STORAGE_ACCT_NAME }}

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    permissions:
      contents: read # for actions/checkout to fetch code
      pull-requests: write # for Azure/static-web-apps-deploy to comment on PRs
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload Files to Azure Storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az storage blob upload-batch --account-name $AZ_STORAGE_ACCT_NAME --auth-mode key -d '$web' -s $SRC_DIR
